AtHour = "at"
ByYearDay = "day"
Every = "every"
InMonthly = "in"
InWeekNo = "in"
OnAllWeek = "on"
OnTheMonthDay = "on the"
OnTheWeekDay = "on the"
OnTheYearDay = "on the"
OnWeekDay = "on"
TheAllWeek = "the"
Until = "until"

[And]
description = "Used for final delimiter in list"
other = "and"

[ByWeekNo]
few = "weeks"
many = "weeks"
one = "week"
other = "weeks"
two = "weeks"

[Day]
few = "days"
many = "days"
one = "day"
other = "days"
two = "days"

[EveryDay]
few = "days"
many = "days"
one = "day"
other = "days"
two = "days"

[Hour]
few = "hours"
many = "hours"
one = "hour"
other = "hours"
two = "hours"

[Minute]
few = "minutes"
many = "minutes"
one = "minute"
other = "minutes"
two = "minutes"

[Month]
few = "months"
many = "months"
one = "month"
other = "months"
two = "months"

[Or]
description = "Used for final delimiter in list"
other = "or"

[TimeCount]
few = "for {{.Count}} times"
many = "for {{.Count}} times"
one = "for {{.Count}} time"
other = "for {{.Count}} times"
two = "for {{.Count}} times"

[Week]
few = "weeks"
many = "weeks"
one = "week"
other = "weeks"
two = "weeks"

[Weekday]
few = "weekdays"
many = "weekdays"
one = "weekday"
other = "weekdays"
two = "weekdays"

[Year]
few = "years"
many = "years"
one = "year"
other = "years"
two = "years"
